language: rust
rust:
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - rust: beta
addons:
  apt:
    packages:
      - libroar-dev
script:
  - cargo build --verbose --release
  - cargo test --verbose --release
